### ISSUE TITLE
Typo/Wrong arguments in wiki.putPage()

### ISSUE THREAD

**Issue by IZSkiSurfer** [Gasol/trac-xmlrpcplugin#3]
In https://github.com/Gasol/trac-xmlrpcplugin/blob/cc8eb153cb4d20c2f29f4f5f5f783858c79081f1/trunk/tracrpc/wiki.py#L154 it should be `attributes.get('comment', req.remote_addr)` so remote_addr gets the default comment. In the current code remote_addr is a further attribute which sets a timestamp for the wiki page which of course fails in /trac/wiki/model.py

**Comment by Gasol** [comment]
Thanks!
